2018-06-28 17:47:02.331 26840 DEBUG nova.osapi_compute.wsgi.server [req-c5c4ba7a-2f7f-48de-8efb-b0df9c1dc537 95cf4ee261b740498c206cbae584ebbe 046e8009a8b544bfbe9ff50b26903464 - default default] (26840) accepted ('10.0.20.26', 53362) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 17:47:02.867 26840 DEBUG nova.api.openstack.wsgi [req-8d19520a-37c9-42ca-aaa0-5e7d23d6e1ca 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Azione: 'create', metodo chiamata: <function version_select at 0x7fea9ff2bf50>, corpo: {"keypair": {"public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOY3mnNzxWBl4PgzYFz39ydNocwZZT412IRGoE7Ap5yTwmAxPy/26mP2hqxnShoC+/dLFswZ3vvd/AqkcFVkFy3euYRbGP19KA0K4Z9mX62to5HHkFtni/2KTEYwAaQy3R5jsO6hUnaKzSCVB4VEAB/hKaiqKkc7kWrxO3/oROhkrcvsOW1MPtxOvQbDA2l/RHOsJz152926GaAvA0EL45JnSWX3GAOPdp8xgGbYgf3/BI5yMtExvjAHDnDo7MJk5xPgxPZtNQxUTPAmeQaTOd4WgwWdfKP1VCLw8d799uMwQHNub/Kn5Bc3DI78lw1oWIeml0qHpior/kwRKMG6cX root@localhost.localdomain\n", "name": "tempest-keypair-1530200757"}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-06-28 17:47:03.001 26840 DEBUG nova.quota [req-8d19520a-37c9-42ca-aaa0-5e7d23d6e1ca 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Getting quotas for project a4257ab4c6fa41fa9a1bbb8768014ddb. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-06-28 17:47:03.012 26840 DEBUG nova.quota [req-8d19520a-37c9-42ca-aaa0-5e7d23d6e1ca 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Getting quotas for user 35abf12be7224ba89c47fb5c86dbc747 and project a4257ab4c6fa41fa9a1bbb8768014ddb. Resources: set(['key_pairs']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-06-28 17:47:03.175 26840 INFO nova.osapi_compute.wsgi.server [req-8d19520a-37c9-42ca-aaa0-5e7d23d6e1ca 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "POST /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/os-keypairs HTTP/1.1" status: 200 len: 997 time: 0.8408370
2018-06-28 17:47:10.454 26841 DEBUG nova.osapi_compute.wsgi.server [req-c80f54f7-614f-4115-b85f-bcedec63f052 - - - - -] (26841) accepted ('10.0.20.26', 53394) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 17:47:10.467 26841 WARNING keystonemiddleware.auth_token [req-c80f54f7-614f-4115-b85f-bcedec63f052 - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-06-28 17:47:12.719 26841 DEBUG nova.api.openstack.wsgi [req-75ccb799-60bb-441d-bb8d-cb1e2da29c02 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<function version_select at 0x7fea9ff67410>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:47:12.759 26841 DEBUG oslo_db.sqlalchemy.engines [req-75ccb799-60bb-441d-bb8d-cb1e2da29c02 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 17:47:12.768 26841 WARNING oslo_db.sqlalchemy.utils [req-75ccb799-60bb-441d-bb8d-cb1e2da29c02 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Unique keys not in sort_keys. The sorting order may be unstable.
2018-06-28 17:47:12.782 26841 WARNING oslo_db.sqlalchemy.utils [req-75ccb799-60bb-441d-bb8d-cb1e2da29c02 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Unique keys not in sort_keys. The sorting order may be unstable.
2018-06-28 17:47:12.795 26841 INFO nova.osapi_compute.wsgi.server [req-75ccb799-60bb-441d-bb8d-cb1e2da29c02 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/os-keypairs HTTP/1.1" status: 200 len: 966 time: 2.3354208
2018-06-28 17:49:32.090 26841 DEBUG nova.osapi_compute.wsgi.server [req-75ccb799-60bb-441d-bb8d-cb1e2da29c02 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] (26841) accepted ('10.0.20.26', 55888) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 17:49:32.465 26841 DEBUG nova.api.openstack.wsgi [req-e9715210-b677-42df-8aa7-e92898c7b8e6 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7feaa099da90>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:49:32.539 26841 INFO nova.api.openstack.wsgi [req-e9715210-b677-42df-8aa7-e92898c7b8e6 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] HTTP exception thrown: Impossibile trovare la tipologia m1.tiny.
2018-06-28 17:49:32.541 26841 DEBUG nova.api.openstack.wsgi [req-e9715210-b677-42df-8aa7-e92898c7b8e6 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Returning 404 to user: Impossibile trovare la tipologia m1.tiny. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 17:49:32.544 26841 INFO nova.osapi_compute.wsgi.server [req-e9715210-b677-42df-8aa7-e92898c7b8e6 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/flavors/m1.tiny HTTP/1.1" status: 404 len: 507 time: 0.4503839
2018-06-28 17:49:32.583 26841 DEBUG nova.api.openstack.wsgi [req-b906bc63-f42a-463e-b070-a91ed80c7f3d 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method FlavorsController.index of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7feaa099d290>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:49:32.664 26841 INFO nova.osapi_compute.wsgi.server [req-b906bc63-f42a-463e-b070-a91ed80c7f3d 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/flavors HTTP/1.1" status: 200 len: 2106 time: 0.0929461
2018-06-28 17:49:32.702 26841 DEBUG nova.api.openstack.wsgi [req-06c84e20-c87c-4587-8c16-c44e924c57c0 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7feaa099da90>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:49:32.742 26841 INFO nova.osapi_compute.wsgi.server [req-06c84e20-c87c-4587-8c16-c44e924c57c0 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/flavors/1 HTTP/1.1" status: 200 len: 819 time: 0.0513120
2018-06-28 17:49:36.841 26841 DEBUG nova.api.openstack.wsgi [req-d21c9798-5074-4156-8e53-827f940b2840 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Azione: 'create', metodo chiamata: <bound method ServersController.create of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa06fdc10>>, corpo: {"server": {"name": "tempest-INSTANCE_SAMPLE-1530200757", "imageRef": "410e3096-de29-4617-b37a-5ff0a083acf2", "key_name": "tempest-keypair-1530200757", "flavorRef": "1", "max_count": 1, "min_count": 1, "networks": [{"uuid": "6ca6deb5-288b-42b6-ab12-54dda733bb52"}], "security_groups": [{"name": "dfb1e1cc-0859-4903-ba51-047c51aaa9f0"}]}} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-06-28 17:49:36.959 26841 DEBUG oslo_concurrency.lockutils [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:49:36.961 26841 DEBUG oslo_concurrency.lockutils [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.003s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:49:36.988 26841 DEBUG oslo_db.sqlalchemy.engines [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 17:49:37.010 26841 DEBUG oslo_concurrency.lockutils [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:49:37.017 26841 DEBUG oslo_concurrency.lockutils [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.007s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:49:37.043 26841 DEBUG oslo_db.sqlalchemy.engines [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 17:49:37.099 26841 WARNING nova.image.glance [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] No protocol specified in for api_server 'http://10.0.20.26:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-06-28 17:49:39.779 26841 DEBUG nova.network.neutronv2.api [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] validate_networks() for [(u'6ca6deb5-288b-42b6-ab12-54dda733bb52', None, None, None)] validate_networks /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:928
2018-06-28 17:49:40.521 26841 DEBUG nova.virt.hardware [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] emulator threads policy constraint: None get_emulator_threads_constraint /usr/lib/python2.7/site-packages/nova/virt/hardware.py:1289
2018-06-28 17:49:41.171 26841 DEBUG nova.quota [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] Getting quotas for project a4257ab4c6fa41fa9a1bbb8768014ddb. Resources: ['metadata_items'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-06-28 17:49:41.198 26841 DEBUG nova.quota [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] Getting quotas for user 35abf12be7224ba89c47fb5c86dbc747 and project a4257ab4c6fa41fa9a1bbb8768014ddb. Resources: ['metadata_items'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-06-28 17:49:41.305 26841 DEBUG nova.quota [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] Getting quotas for project a4257ab4c6fa41fa9a1bbb8768014ddb. Resources: ['injected_files'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-06-28 17:49:41.317 26841 DEBUG nova.quota [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] Getting quotas for user 35abf12be7224ba89c47fb5c86dbc747 and project a4257ab4c6fa41fa9a1bbb8768014ddb. Resources: ['injected_files'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-06-28 17:49:41.391 26841 DEBUG nova.quota [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] Getting quotas for project a4257ab4c6fa41fa9a1bbb8768014ddb. Resources: ['injected_file_content_bytes', 'injected_file_path_bytes'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-06-28 17:49:41.405 26841 DEBUG nova.quota [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] Getting quotas for user 35abf12be7224ba89c47fb5c86dbc747 and project a4257ab4c6fa41fa9a1bbb8768014ddb. Resources: ['injected_file_content_bytes', 'injected_file_path_bytes'] _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-06-28 17:49:41.465 26841 DEBUG nova.context [req-0505103e-419b-4691-9735-541a2980e497 - - - - -] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),a007229b-3aa8-4995-b876-a3a23b26e694(default) load_cells /usr/lib/python2.7/site-packages/nova/context.py:508
2018-06-28 17:49:41.467 26841 DEBUG oslo_concurrency.lockutils [req-d21c9798-5074-4156-8e53-827f940b2840 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:49:41.468 26841 DEBUG oslo_concurrency.lockutils [req-d21c9798-5074-4156-8e53-827f940b2840 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:49:41.469 26841 DEBUG oslo_concurrency.lockutils [req-d21c9798-5074-4156-8e53-827f940b2840 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:49:41.470 26841 DEBUG oslo_concurrency.lockutils [req-d21c9798-5074-4156-8e53-827f940b2840 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:49:41.534 26841 DEBUG nova.quota [req-d21c9798-5074-4156-8e53-827f940b2840 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Getting quotas for project a4257ab4c6fa41fa9a1bbb8768014ddb. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-06-28 17:49:41.543 26841 DEBUG nova.quota [req-d21c9798-5074-4156-8e53-827f940b2840 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Getting quotas for user 35abf12be7224ba89c47fb5c86dbc747 and project a4257ab4c6fa41fa9a1bbb8768014ddb. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-06-28 17:49:41.582 26841 DEBUG nova.compute.api [req-d21c9798-5074-4156-8e53-827f940b2840 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Going to run 1 instances... _provision_instances /usr/lib/python2.7/site-packages/nova/compute/api.py:891
2018-06-28 17:49:41.644 26841 DEBUG nova.compute.api [req-d21c9798-5074-4156-8e53-827f940b2840 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] [instance: 071f01a3-1f27-4a26-aaec-b12423ffa7aa] block_device_mapping [BlockDeviceMapping(attachment_id=<?>,boot_index=0,connection_info=None,created_at=<?>,delete_on_termination=True,deleted=<?>,deleted_at=<?>,destination_type='local',device_name=None,device_type='disk',disk_bus=None,guest_format=None,id=<?>,image_id='410e3096-de29-4617-b37a-5ff0a083acf2',instance=<?>,instance_uuid=<?>,no_device=False,snapshot_id=None,source_type='image',tag=None,updated_at=<?>,volume_id=None,volume_size=None)] _bdm_validate_set_size_and_instance /usr/lib/python2.7/site-packages/nova/compute/api.py:1268
2018-06-28 17:49:41.994 26841 INFO nova.osapi_compute.wsgi.server [req-d21c9798-5074-4156-8e53-827f940b2840 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "POST /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers HTTP/1.1" status: 202 len: 989 time: 5.1733370
2018-06-28 17:49:42.062 26841 DEBUG nova.api.openstack.wsgi [req-d34c1259-c15b-4987-a954-6a3243aecc75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa0592210>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:49:42.068 26841 DEBUG nova.compute.api [req-d34c1259-c15b-4987-a954-6a3243aecc75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] [instance: 071f01a3-1f27-4a26-aaec-b12423ffa7aa] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 17:49:42.201 26841 DEBUG nova.policy [req-d34c1259-c15b-4987-a954-6a3243aecc75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'35abf12be7224ba89c47fb5c86dbc747', 'roles': [u'admin'], 'user_domain_id': u'02e89a8673da41529ece5743b8bdc4b1', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'a4257ab4c6fa41fa9a1bbb8768014ddb', 'project_domain_id': u'02e89a8673da41529ece5743b8bdc4b1'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 17:49:42.350 26841 INFO nova.osapi_compute.wsgi.server [req-d34c1259-c15b-4987-a954-6a3243aecc75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers/071f01a3-1f27-4a26-aaec-b12423ffa7aa HTTP/1.1" status: 200 len: 1857 time: 0.3180749
2018-06-28 17:49:42.404 26841 DEBUG nova.api.openstack.wsgi [req-fc6d569e-2ec4-4997-81ad-8b13165c2bd5 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7feaa099da90>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:49:42.429 26841 INFO nova.osapi_compute.wsgi.server [req-fc6d569e-2ec4-4997-81ad-8b13165c2bd5 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/flavors/1 HTTP/1.1" status: 200 len: 819 time: 0.0323720
2018-06-28 17:49:48.631 26841 DEBUG nova.osapi_compute.wsgi.server [req-fc6d569e-2ec4-4997-81ad-8b13165c2bd5 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] (26841) accepted ('10.0.20.26', 57016) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 17:49:49.213 26841 INFO nova.osapi_compute.wsgi.server [req-cc894968-98a6-45f1-8655-031027391445 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb HTTP/1.1" status: 404 len: 382 time: 0.5780921
2018-06-28 17:49:49.242 26841 DEBUG nova.api.openstack.wsgi [req-50ef602c-0f5b-4285-b04d-fec942f4d94e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7feaa0a91ed0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:49:49.245 26841 INFO nova.osapi_compute.wsgi.server [req-50ef602c-0f5b-4285-b04d-fec942f4d94e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0169780
2018-06-28 17:49:49.643 26841 DEBUG nova.api.openstack.wsgi [req-8694963d-6475-4984-9288-f69de11c05b7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa06b2d50>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:49:49.651 26841 DEBUG nova.compute.api [req-8694963d-6475-4984-9288-f69de11c05b7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Searching by: {'deleted': False, 'project_id': u'a4257ab4c6fa41fa9a1bbb8768014ddb', u'name': u'tempest-INSTANCE_SAMPLE-1530200757'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 17:49:49.670 26841 DEBUG oslo_concurrency.lockutils [req-8694963d-6475-4984-9288-f69de11c05b7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:49:49.671 26841 DEBUG oslo_concurrency.lockutils [req-8694963d-6475-4984-9288-f69de11c05b7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:49:49.782 26841 DEBUG nova.compute.api [req-8694963d-6475-4984-9288-f69de11c05b7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),a007229b-3aa8-4995-b876-a3a23b26e694(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-06-28 17:49:49.784 26841 DEBUG nova.compute.api [req-8694963d-6475-4984-9288-f69de11c05b7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 17:49:49.784 26841 DEBUG nova.compute.api [req-8694963d-6475-4984-9288-f69de11c05b7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Listing 1000 instances in cell a007229b-3aa8-4995-b876-a3a23b26e694(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 17:49:49.787 26841 DEBUG oslo_concurrency.lockutils [req-8694963d-6475-4984-9288-f69de11c05b7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:49:49.788 26841 DEBUG oslo_concurrency.lockutils [req-8694963d-6475-4984-9288-f69de11c05b7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:49:49.924 26841 INFO nova.osapi_compute.wsgi.server [req-8694963d-6475-4984-9288-f69de11c05b7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers?name=tempest-INSTANCE_SAMPLE-1530200757 HTTP/1.1" status: 200 len: 786 time: 0.2936959
2018-06-28 17:49:49.964 26841 DEBUG nova.api.openstack.wsgi [req-22937b21-d5e8-4c02-a783-53459d3b89d7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa0592210>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:49:49.968 26841 DEBUG nova.compute.api [req-22937b21-d5e8-4c02-a783-53459d3b89d7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] [instance: 071f01a3-1f27-4a26-aaec-b12423ffa7aa] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 17:49:49.980 26841 DEBUG oslo_concurrency.lockutils [req-22937b21-d5e8-4c02-a783-53459d3b89d7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:49:49.981 26841 DEBUG oslo_concurrency.lockutils [req-22937b21-d5e8-4c02-a783-53459d3b89d7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:49:50.194 26841 DEBUG nova.objects.instance [req-22937b21-d5e8-4c02-a783-53459d3b89d7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lazy-loading 'services' on Instance uuid 071f01a3-1f27-4a26-aaec-b12423ffa7aa obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-06-28 17:49:50.332 26841 DEBUG nova.policy [req-22937b21-d5e8-4c02-a783-53459d3b89d7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'35abf12be7224ba89c47fb5c86dbc747', 'roles': [u'admin'], 'user_domain_id': u'02e89a8673da41529ece5743b8bdc4b1', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'a4257ab4c6fa41fa9a1bbb8768014ddb', 'project_domain_id': u'02e89a8673da41529ece5743b8bdc4b1'} authorize /usr/lib/python2.7/site-packages/nova/policy.py:168
2018-06-28 17:49:50.924 26841 INFO nova.osapi_compute.wsgi.server [req-22937b21-d5e8-4c02-a783-53459d3b89d7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers/071f01a3-1f27-4a26-aaec-b12423ffa7aa HTTP/1.1" status: 200 len: 2363 time: 0.9782312
2018-06-28 17:49:57.391 26841 DEBUG nova.osapi_compute.wsgi.server [req-22937b21-d5e8-4c02-a783-53459d3b89d7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] (26841) accepted ('10.0.20.26', 57108) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 17:49:57.674 26841 DEBUG nova.api.openstack.wsgi [req-706aedc8-2f9f-4aef-92d4-27e4748c35e0 b04a8c34c4a64df7842a8b81b478c604 0d772b180b3c41e2ae2eba61c236b149 - default default] Azione: 'create', metodo chiamata: <bound method ServerExternalEventsController.create of <nova.api.openstack.compute.server_external_events.ServerExternalEventsController object at 0x7feaa0876990>>, corpo: {"events": [{"tag": "69dbfa50-aae4-4d39-abe9-57704046b562", "name": "network-changed", "server_uuid": "071f01a3-1f27-4a26-aaec-b12423ffa7aa"}]} _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:609
2018-06-28 17:49:57.695 26841 DEBUG oslo_concurrency.lockutils [req-706aedc8-2f9f-4aef-92d4-27e4748c35e0 b04a8c34c4a64df7842a8b81b478c604 0d772b180b3c41e2ae2eba61c236b149 - default default] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:49:57.695 26841 DEBUG oslo_concurrency.lockutils [req-706aedc8-2f9f-4aef-92d4-27e4748c35e0 b04a8c34c4a64df7842a8b81b478c604 0d772b180b3c41e2ae2eba61c236b149 - default default] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:49:57.723 26841 INFO nova.api.openstack.compute.server_external_events [req-706aedc8-2f9f-4aef-92d4-27e4748c35e0 b04a8c34c4a64df7842a8b81b478c604 0d772b180b3c41e2ae2eba61c236b149 - default default] Creating event network-changed:69dbfa50-aae4-4d39-abe9-57704046b562 for instance 071f01a3-1f27-4a26-aaec-b12423ffa7aa on localhost.localdomain
2018-06-28 17:49:57.777 26841 INFO nova.osapi_compute.wsgi.server [req-706aedc8-2f9f-4aef-92d4-27e4748c35e0 b04a8c34c4a64df7842a8b81b478c604 0d772b180b3c41e2ae2eba61c236b149 - default default] 10.0.20.26 "POST /v2.1/0d772b180b3c41e2ae2eba61c236b149/os-server-external-events HTTP/1.1" status: 200 len: 578 time: 0.3775129
2018-06-28 17:49:58.548 26841 DEBUG nova.osapi_compute.wsgi.server [req-706aedc8-2f9f-4aef-92d4-27e4748c35e0 b04a8c34c4a64df7842a8b81b478c604 0d772b180b3c41e2ae2eba61c236b149 - default default] (26841) accepted ('10.0.20.26', 57126) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 17:49:59.016 26841 INFO nova.osapi_compute.wsgi.server [req-3e2d2c4f-7907-4969-a184-0b10e4cb66b9 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb HTTP/1.1" status: 404 len: 382 time: 0.4640739
2018-06-28 17:49:59.044 26841 DEBUG nova.api.openstack.wsgi [req-b031bde9-a4b9-4d9f-92f9-e43dfcddc8d7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7feaa0a91ed0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:49:59.054 26841 INFO nova.osapi_compute.wsgi.server [req-b031bde9-a4b9-4d9f-92f9-e43dfcddc8d7 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0232151
2018-06-28 17:49:59.382 26841 DEBUG nova.api.openstack.wsgi [req-1033e06a-2b50-47e8-8d8e-de991382cf07 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa06b2d50>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:49:59.390 26841 DEBUG nova.compute.api [req-1033e06a-2b50-47e8-8d8e-de991382cf07 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Searching by: {'deleted': False, 'project_id': u'a4257ab4c6fa41fa9a1bbb8768014ddb', u'name': u'tempest-INSTANCE_SAMPLE-1530200757'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 17:49:59.407 26841 DEBUG oslo_concurrency.lockutils [req-1033e06a-2b50-47e8-8d8e-de991382cf07 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:49:59.408 26841 DEBUG oslo_concurrency.lockutils [req-1033e06a-2b50-47e8-8d8e-de991382cf07 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:49:59.494 26841 DEBUG nova.compute.api [req-1033e06a-2b50-47e8-8d8e-de991382cf07 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 17:49:59.496 26841 DEBUG nova.compute.api [req-1033e06a-2b50-47e8-8d8e-de991382cf07 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Listing 1000 instances in cell a007229b-3aa8-4995-b876-a3a23b26e694(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 17:49:59.497 26841 DEBUG oslo_concurrency.lockutils [req-1033e06a-2b50-47e8-8d8e-de991382cf07 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:49:59.498 26841 DEBUG oslo_concurrency.lockutils [req-1033e06a-2b50-47e8-8d8e-de991382cf07 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:49:59.605 26841 INFO nova.osapi_compute.wsgi.server [req-1033e06a-2b50-47e8-8d8e-de991382cf07 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers?name=tempest-INSTANCE_SAMPLE-1530200757 HTTP/1.1" status: 200 len: 786 time: 0.2326250
2018-06-28 17:49:59.629 26841 DEBUG nova.api.openstack.wsgi [req-1424b1fa-1029-4ffc-b364-33ee5fab0595 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa0592210>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:49:59.633 26841 DEBUG nova.compute.api [req-1424b1fa-1029-4ffc-b364-33ee5fab0595 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] [instance: 071f01a3-1f27-4a26-aaec-b12423ffa7aa] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 17:49:59.642 26841 DEBUG oslo_concurrency.lockutils [req-1424b1fa-1029-4ffc-b364-33ee5fab0595 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:49:59.643 26841 DEBUG oslo_concurrency.lockutils [req-1424b1fa-1029-4ffc-b364-33ee5fab0595 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions [req-1424b1fa-1029-4ffc-b364-33ee5fab0595 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Unexpected exception in API method: TypeError: 'NoneType' object is not iterable
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions Traceback (most recent call last):
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/extensions.py", line 336, in wrapped
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions     return f(*args, **kwargs)
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/servers.py", line 442, in show
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions     return self._view_builder.show(req, instance)
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 145, in show
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions     extend_address),
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 252, in _get_addresses
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions     networks = common.get_networks_for_instance(context, instance)
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 326, in get_networks_for_instance
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions     return get_networks_for_instance_from_nw_info(nw_info)
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 293, in get_networks_for_instance_from_nw_info
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions     for vif in nw_info:
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions TypeError: 'NoneType' object is not iterable
2018-06-28 17:49:59.761 26841 ERROR nova.api.openstack.extensions 
2018-06-28 17:49:59.771 26841 INFO nova.api.openstack.wsgi [req-1424b1fa-1029-4ffc-b364-33ee5fab0595 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] HTTP exception thrown: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'>
2018-06-28 17:49:59.772 26841 DEBUG nova.api.openstack.wsgi [req-1424b1fa-1029-4ffc-b364-33ee5fab0595 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Returning 500 to user: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'> __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 17:49:59.775 26841 INFO nova.osapi_compute.wsgi.server [req-1424b1fa-1029-4ffc-b364-33ee5fab0595 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers/071f01a3-1f27-4a26-aaec-b12423ffa7aa HTTP/1.1" status: 500 len: 623 time: 0.1555128
2018-06-28 17:50:08.685 26841 DEBUG nova.osapi_compute.wsgi.server [req-1424b1fa-1029-4ffc-b364-33ee5fab0595 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] (26841) accepted ('10.0.20.26', 57186) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 17:50:09.117 26841 INFO nova.osapi_compute.wsgi.server [req-ce68a473-9692-47b2-999f-3ebf660d10c1 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb HTTP/1.1" status: 404 len: 382 time: 0.4273779
2018-06-28 17:50:09.137 26841 DEBUG nova.api.openstack.wsgi [req-909ed8cc-1bad-40ca-9b73-b891532b8633 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7feaa0a91ed0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:50:09.139 26841 INFO nova.osapi_compute.wsgi.server [req-909ed8cc-1bad-40ca-9b73-b891532b8633 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0095088
2018-06-28 17:50:09.467 26841 DEBUG nova.api.openstack.wsgi [req-df1a2e39-8e6d-4ffb-861a-a5db70235a92 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa06b2d50>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:50:09.475 26841 DEBUG nova.compute.api [req-df1a2e39-8e6d-4ffb-861a-a5db70235a92 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Searching by: {'deleted': False, 'project_id': u'a4257ab4c6fa41fa9a1bbb8768014ddb', u'name': u'tempest-INSTANCE_SAMPLE-1530200757'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 17:50:09.495 26841 DEBUG oslo_concurrency.lockutils [req-df1a2e39-8e6d-4ffb-861a-a5db70235a92 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:50:09.496 26841 DEBUG oslo_concurrency.lockutils [req-df1a2e39-8e6d-4ffb-861a-a5db70235a92 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:50:09.570 26841 DEBUG nova.compute.api [req-df1a2e39-8e6d-4ffb-861a-a5db70235a92 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 17:50:09.572 26841 DEBUG nova.compute.api [req-df1a2e39-8e6d-4ffb-861a-a5db70235a92 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Listing 1000 instances in cell a007229b-3aa8-4995-b876-a3a23b26e694(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 17:50:09.573 26841 DEBUG oslo_concurrency.lockutils [req-df1a2e39-8e6d-4ffb-861a-a5db70235a92 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:50:09.574 26841 DEBUG oslo_concurrency.lockutils [req-df1a2e39-8e6d-4ffb-861a-a5db70235a92 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:50:09.646 26841 INFO nova.osapi_compute.wsgi.server [req-df1a2e39-8e6d-4ffb-861a-a5db70235a92 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers?name=tempest-INSTANCE_SAMPLE-1530200757 HTTP/1.1" status: 200 len: 786 time: 0.1959109
2018-06-28 17:50:09.676 26841 DEBUG nova.api.openstack.wsgi [req-1108cf60-c0bd-42c6-98fe-c8582c4e2bce 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa0592210>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:50:09.682 26841 DEBUG nova.compute.api [req-1108cf60-c0bd-42c6-98fe-c8582c4e2bce 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] [instance: 071f01a3-1f27-4a26-aaec-b12423ffa7aa] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 17:50:09.696 26841 DEBUG oslo_concurrency.lockutils [req-1108cf60-c0bd-42c6-98fe-c8582c4e2bce 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:50:09.697 26841 DEBUG oslo_concurrency.lockutils [req-1108cf60-c0bd-42c6-98fe-c8582c4e2bce 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions [req-1108cf60-c0bd-42c6-98fe-c8582c4e2bce 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Unexpected exception in API method: TypeError: 'NoneType' object is not iterable
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions Traceback (most recent call last):
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/extensions.py", line 336, in wrapped
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions     return f(*args, **kwargs)
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/servers.py", line 442, in show
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions     return self._view_builder.show(req, instance)
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 145, in show
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions     extend_address),
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 252, in _get_addresses
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions     networks = common.get_networks_for_instance(context, instance)
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 326, in get_networks_for_instance
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions     return get_networks_for_instance_from_nw_info(nw_info)
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 293, in get_networks_for_instance_from_nw_info
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions     for vif in nw_info:
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions TypeError: 'NoneType' object is not iterable
2018-06-28 17:50:09.811 26841 ERROR nova.api.openstack.extensions 
2018-06-28 17:50:09.814 26841 INFO nova.api.openstack.wsgi [req-1108cf60-c0bd-42c6-98fe-c8582c4e2bce 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] HTTP exception thrown: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'>
2018-06-28 17:50:09.815 26841 DEBUG nova.api.openstack.wsgi [req-1108cf60-c0bd-42c6-98fe-c8582c4e2bce 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Returning 500 to user: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'> __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 17:50:09.818 26841 INFO nova.osapi_compute.wsgi.server [req-1108cf60-c0bd-42c6-98fe-c8582c4e2bce 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers/071f01a3-1f27-4a26-aaec-b12423ffa7aa HTTP/1.1" status: 500 len: 623 time: 0.1538432
2018-06-28 17:50:17.073 26835 DEBUG nova.api.openstack.wsgi [req-df2ef5ba-3397-4fe3-b6fe-b397d9d3d85a 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa061ff50>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:50:17.090 26835 DEBUG nova.compute.api [req-df2ef5ba-3397-4fe3-b6fe-b397d9d3d85a 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Searching by: {u'changes-since': datetime.datetime(2018, 6, 28, 15, 45, 19, 80365, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 17:50:17.118 26835 DEBUG oslo_concurrency.lockutils [req-df2ef5ba-3397-4fe3-b6fe-b397d9d3d85a 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:50:17.119 26835 DEBUG oslo_concurrency.lockutils [req-df2ef5ba-3397-4fe3-b6fe-b397d9d3d85a 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:50:17.242 26835 DEBUG nova.compute.api [req-df2ef5ba-3397-4fe3-b6fe-b397d9d3d85a 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 17:50:17.245 26835 DEBUG nova.compute.api [req-df2ef5ba-3397-4fe3-b6fe-b397d9d3d85a 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Listing 1000 instances in cell a007229b-3aa8-4995-b876-a3a23b26e694(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 17:50:17.246 26835 DEBUG oslo_concurrency.lockutils [req-df2ef5ba-3397-4fe3-b6fe-b397d9d3d85a 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:50:17.249 26835 DEBUG oslo_concurrency.lockutils [req-df2ef5ba-3397-4fe3-b6fe-b397d9d3d85a 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions [req-df2ef5ba-3397-4fe3-b6fe-b397d9d3d85a 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Unexpected exception in API method: TypeError: 'NoneType' object is not iterable
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions Traceback (most recent call last):
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/extensions.py", line 336, in wrapped
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions     return f(*args, **kwargs)
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/validation/__init__.py", line 181, in wrapper
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions     return func(*args, **kwargs)
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/validation/__init__.py", line 181, in wrapper
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions     return func(*args, **kwargs)
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/servers.py", line 168, in detail
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions     servers = self._get_servers(req, is_detail=True)
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/servers.py", line 323, in _get_servers
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions     response = self._view_builder.detail(req, instance_list)
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 199, in detail
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions     show_extra_specs)
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 213, in _list_view
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions     for server in servers]
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 145, in show
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions     extend_address),
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 252, in _get_addresses
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions     networks = common.get_networks_for_instance(context, instance)
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 326, in get_networks_for_instance
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions     return get_networks_for_instance_from_nw_info(nw_info)
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 293, in get_networks_for_instance_from_nw_info
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions     for vif in nw_info:
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions TypeError: 'NoneType' object is not iterable
2018-06-28 17:50:17.463 26835 ERROR nova.api.openstack.extensions 
2018-06-28 17:50:17.479 26835 INFO nova.api.openstack.wsgi [req-df2ef5ba-3397-4fe3-b6fe-b397d9d3d85a 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] HTTP exception thrown: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'>
2018-06-28 17:50:17.480 26835 DEBUG nova.api.openstack.wsgi [req-df2ef5ba-3397-4fe3-b6fe-b397d9d3d85a 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Returning 500 to user: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'> __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 17:50:17.484 26835 INFO nova.osapi_compute.wsgi.server [req-df2ef5ba-3397-4fe3-b6fe-b397d9d3d85a 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] 10.0.20.26 "GET /v2.1/0d772b180b3c41e2ae2eba61c236b149/servers/detail?all_tenants=True&changes-since=2018-06-28T15%3A45%3A19.080365%2B00%3A00 HTTP/1.1" status: 500 len: 621 time: 0.4303200
2018-06-28 17:50:22.646 26841 DEBUG nova.osapi_compute.wsgi.server [req-1108cf60-c0bd-42c6-98fe-c8582c4e2bce 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] (26841) accepted ('10.0.20.26', 57230) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 17:50:23.280 26841 INFO nova.osapi_compute.wsgi.server [req-0c22bf6f-20e7-4bd2-a2ca-98fdf8d03317 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb HTTP/1.1" status: 404 len: 382 time: 0.6302521
2018-06-28 17:50:23.313 26841 DEBUG nova.api.openstack.wsgi [req-4e326cf1-252f-4653-af65-bbb22e0bef84 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7feaa0a91ed0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:50:23.316 26841 INFO nova.osapi_compute.wsgi.server [req-4e326cf1-252f-4653-af65-bbb22e0bef84 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0172551
2018-06-28 17:50:23.691 26841 DEBUG nova.api.openstack.wsgi [req-217f440d-a250-41cf-a05d-3970f3e09fb2 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa06b2d50>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:50:23.698 26841 DEBUG nova.compute.api [req-217f440d-a250-41cf-a05d-3970f3e09fb2 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Searching by: {'deleted': False, 'project_id': u'a4257ab4c6fa41fa9a1bbb8768014ddb', u'name': u'tempest-INSTANCE_SAMPLE-1530200757'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 17:50:23.717 26841 DEBUG oslo_concurrency.lockutils [req-217f440d-a250-41cf-a05d-3970f3e09fb2 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:50:23.717 26841 DEBUG oslo_concurrency.lockutils [req-217f440d-a250-41cf-a05d-3970f3e09fb2 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:50:23.772 26841 DEBUG nova.compute.api [req-217f440d-a250-41cf-a05d-3970f3e09fb2 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 17:50:23.772 26841 DEBUG nova.compute.api [req-217f440d-a250-41cf-a05d-3970f3e09fb2 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Listing 1000 instances in cell a007229b-3aa8-4995-b876-a3a23b26e694(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 17:50:23.774 26841 DEBUG oslo_concurrency.lockutils [req-217f440d-a250-41cf-a05d-3970f3e09fb2 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:50:23.775 26841 DEBUG oslo_concurrency.lockutils [req-217f440d-a250-41cf-a05d-3970f3e09fb2 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:50:23.867 26841 INFO nova.osapi_compute.wsgi.server [req-217f440d-a250-41cf-a05d-3970f3e09fb2 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers?name=tempest-INSTANCE_SAMPLE-1530200757 HTTP/1.1" status: 200 len: 786 time: 0.1896269
2018-06-28 17:50:23.903 26841 DEBUG nova.api.openstack.wsgi [req-2feec483-8b76-4ee6-971f-cf09d0dfa161 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa0592210>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:50:23.909 26841 DEBUG nova.compute.api [req-2feec483-8b76-4ee6-971f-cf09d0dfa161 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] [instance: 071f01a3-1f27-4a26-aaec-b12423ffa7aa] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 17:50:23.928 26841 DEBUG oslo_concurrency.lockutils [req-2feec483-8b76-4ee6-971f-cf09d0dfa161 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:50:23.929 26841 DEBUG oslo_concurrency.lockutils [req-2feec483-8b76-4ee6-971f-cf09d0dfa161 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions [req-2feec483-8b76-4ee6-971f-cf09d0dfa161 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Unexpected exception in API method: TypeError: 'NoneType' object is not iterable
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions Traceback (most recent call last):
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/extensions.py", line 336, in wrapped
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions     return f(*args, **kwargs)
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/servers.py", line 442, in show
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions     return self._view_builder.show(req, instance)
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 145, in show
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions     extend_address),
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 252, in _get_addresses
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions     networks = common.get_networks_for_instance(context, instance)
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 326, in get_networks_for_instance
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions     return get_networks_for_instance_from_nw_info(nw_info)
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 293, in get_networks_for_instance_from_nw_info
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions     for vif in nw_info:
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions TypeError: 'NoneType' object is not iterable
2018-06-28 17:50:24.047 26841 ERROR nova.api.openstack.extensions 
2018-06-28 17:50:24.049 26841 INFO nova.api.openstack.wsgi [req-2feec483-8b76-4ee6-971f-cf09d0dfa161 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] HTTP exception thrown: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'>
2018-06-28 17:50:24.050 26841 DEBUG nova.api.openstack.wsgi [req-2feec483-8b76-4ee6-971f-cf09d0dfa161 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Returning 500 to user: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'> __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 17:50:24.052 26841 INFO nova.osapi_compute.wsgi.server [req-2feec483-8b76-4ee6-971f-cf09d0dfa161 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers/071f01a3-1f27-4a26-aaec-b12423ffa7aa HTTP/1.1" status: 500 len: 623 time: 0.1635292
2018-06-28 17:50:39.278 26837 DEBUG nova.osapi_compute.wsgi.server [req-c80f54f7-614f-4115-b85f-bcedec63f052 - - - - -] (26837) accepted ('10.0.20.26', 57256) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 17:50:39.294 26837 WARNING keystonemiddleware.auth_token [req-c80f54f7-614f-4115-b85f-bcedec63f052 - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-06-28 17:50:41.449 26837 INFO nova.osapi_compute.wsgi.server [req-22a02352-b306-448b-b3c0-f3cba2a50885 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb HTTP/1.1" status: 404 len: 382 time: 2.1633651
2018-06-28 17:50:41.476 26837 DEBUG nova.api.openstack.wsgi [req-a416283c-86e5-4827-a33d-a94c665659c9 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7feaa0a91ed0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:50:41.480 26837 INFO nova.osapi_compute.wsgi.server [req-a416283c-86e5-4827-a33d-a94c665659c9 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0170639
2018-06-28 17:50:41.901 26837 DEBUG nova.api.openstack.wsgi [req-526c92a3-09dc-41ec-bda5-cd75238a955e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa06b2d50>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:50:41.916 26837 DEBUG nova.compute.api [req-526c92a3-09dc-41ec-bda5-cd75238a955e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Searching by: {'deleted': False, 'project_id': u'a4257ab4c6fa41fa9a1bbb8768014ddb', u'name': u'tempest-INSTANCE_SAMPLE-1530200757'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 17:50:41.970 26837 DEBUG oslo_db.sqlalchemy.engines [req-526c92a3-09dc-41ec-bda5-cd75238a955e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 17:50:42.004 26837 DEBUG oslo_concurrency.lockutils [req-526c92a3-09dc-41ec-bda5-cd75238a955e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:50:42.006 26837 DEBUG oslo_concurrency.lockutils [req-526c92a3-09dc-41ec-bda5-cd75238a955e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:50:42.024 26837 DEBUG oslo_db.sqlalchemy.engines [req-526c92a3-09dc-41ec-bda5-cd75238a955e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 17:50:42.107 26837 DEBUG nova.compute.api [req-526c92a3-09dc-41ec-bda5-cd75238a955e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),a007229b-3aa8-4995-b876-a3a23b26e694(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-06-28 17:50:42.108 26837 DEBUG nova.compute.api [req-526c92a3-09dc-41ec-bda5-cd75238a955e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 17:50:42.108 26837 DEBUG nova.compute.api [req-526c92a3-09dc-41ec-bda5-cd75238a955e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Listing 1000 instances in cell a007229b-3aa8-4995-b876-a3a23b26e694(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 17:50:42.109 26837 DEBUG oslo_concurrency.lockutils [req-526c92a3-09dc-41ec-bda5-cd75238a955e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:50:42.113 26837 DEBUG oslo_concurrency.lockutils [req-526c92a3-09dc-41ec-bda5-cd75238a955e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:50:42.130 26837 DEBUG oslo_db.sqlalchemy.engines [req-526c92a3-09dc-41ec-bda5-cd75238a955e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 17:50:42.207 26837 INFO nova.osapi_compute.wsgi.server [req-526c92a3-09dc-41ec-bda5-cd75238a955e 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers?name=tempest-INSTANCE_SAMPLE-1530200757 HTTP/1.1" status: 200 len: 786 time: 0.3216231
2018-06-28 17:50:42.235 26837 DEBUG nova.api.openstack.wsgi [req-7ba8aed9-173e-4793-99d6-dd934d888678 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa0592210>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:50:42.242 26837 DEBUG nova.compute.api [req-7ba8aed9-173e-4793-99d6-dd934d888678 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] [instance: 071f01a3-1f27-4a26-aaec-b12423ffa7aa] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 17:50:42.275 26837 DEBUG oslo_concurrency.lockutils [req-7ba8aed9-173e-4793-99d6-dd934d888678 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:50:42.276 26837 DEBUG oslo_concurrency.lockutils [req-7ba8aed9-173e-4793-99d6-dd934d888678 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions [req-7ba8aed9-173e-4793-99d6-dd934d888678 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Unexpected exception in API method: TypeError: 'NoneType' object is not iterable
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions Traceback (most recent call last):
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/extensions.py", line 336, in wrapped
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions     return f(*args, **kwargs)
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/servers.py", line 442, in show
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions     return self._view_builder.show(req, instance)
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 145, in show
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions     extend_address),
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 252, in _get_addresses
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions     networks = common.get_networks_for_instance(context, instance)
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 326, in get_networks_for_instance
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions     return get_networks_for_instance_from_nw_info(nw_info)
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 293, in get_networks_for_instance_from_nw_info
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions     for vif in nw_info:
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions TypeError: 'NoneType' object is not iterable
2018-06-28 17:50:42.655 26837 ERROR nova.api.openstack.extensions 
2018-06-28 17:50:42.658 26837 INFO nova.api.openstack.wsgi [req-7ba8aed9-173e-4793-99d6-dd934d888678 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] HTTP exception thrown: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'>
2018-06-28 17:50:42.658 26837 DEBUG nova.api.openstack.wsgi [req-7ba8aed9-173e-4793-99d6-dd934d888678 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Returning 500 to user: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'> __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 17:50:42.660 26837 INFO nova.osapi_compute.wsgi.server [req-7ba8aed9-173e-4793-99d6-dd934d888678 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers/071f01a3-1f27-4a26-aaec-b12423ffa7aa HTTP/1.1" status: 500 len: 623 time: 0.4396389
2018-06-28 17:50:53.058 26835 DEBUG nova.api.openstack.wsgi [req-e4d0303d-0c46-4061-8d46-5c377b5b216e 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa061ff50>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:50:53.072 26835 DEBUG nova.compute.api [req-e4d0303d-0c46-4061-8d46-5c377b5b216e 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Searching by: {u'changes-since': datetime.datetime(2018, 6, 28, 15, 45, 54, 642651, tzinfo=<FixedOffset u'+00:00' datetime.timedelta(0)>)} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 17:50:53.095 26835 DEBUG oslo_concurrency.lockutils [req-e4d0303d-0c46-4061-8d46-5c377b5b216e 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:50:53.096 26835 DEBUG oslo_concurrency.lockutils [req-e4d0303d-0c46-4061-8d46-5c377b5b216e 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:50:53.215 26835 DEBUG nova.compute.api [req-e4d0303d-0c46-4061-8d46-5c377b5b216e 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 17:50:53.216 26835 DEBUG nova.compute.api [req-e4d0303d-0c46-4061-8d46-5c377b5b216e 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Listing 1000 instances in cell a007229b-3aa8-4995-b876-a3a23b26e694(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 17:50:53.217 26835 DEBUG oslo_concurrency.lockutils [req-e4d0303d-0c46-4061-8d46-5c377b5b216e 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:50:53.219 26835 DEBUG oslo_concurrency.lockutils [req-e4d0303d-0c46-4061-8d46-5c377b5b216e 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions [req-e4d0303d-0c46-4061-8d46-5c377b5b216e 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Unexpected exception in API method: TypeError: 'NoneType' object is not iterable
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions Traceback (most recent call last):
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/extensions.py", line 336, in wrapped
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions     return f(*args, **kwargs)
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/validation/__init__.py", line 181, in wrapper
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions     return func(*args, **kwargs)
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/validation/__init__.py", line 181, in wrapper
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions     return func(*args, **kwargs)
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/servers.py", line 168, in detail
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions     servers = self._get_servers(req, is_detail=True)
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/servers.py", line 323, in _get_servers
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions     response = self._view_builder.detail(req, instance_list)
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 199, in detail
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions     show_extra_specs)
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 213, in _list_view
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions     for server in servers]
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 145, in show
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions     extend_address),
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 252, in _get_addresses
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions     networks = common.get_networks_for_instance(context, instance)
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 326, in get_networks_for_instance
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions     return get_networks_for_instance_from_nw_info(nw_info)
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 293, in get_networks_for_instance_from_nw_info
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions     for vif in nw_info:
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions TypeError: 'NoneType' object is not iterable
2018-06-28 17:50:53.364 26835 ERROR nova.api.openstack.extensions 
2018-06-28 17:50:53.368 26835 INFO nova.api.openstack.wsgi [req-e4d0303d-0c46-4061-8d46-5c377b5b216e 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] HTTP exception thrown: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'>
2018-06-28 17:50:53.370 26835 DEBUG nova.api.openstack.wsgi [req-e4d0303d-0c46-4061-8d46-5c377b5b216e 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] Returning 500 to user: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'> __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 17:50:53.374 26835 INFO nova.osapi_compute.wsgi.server [req-e4d0303d-0c46-4061-8d46-5c377b5b216e 34449420d71643ff9c143c132ecdb7b4 0d772b180b3c41e2ae2eba61c236b149 - default default] 10.0.20.26 "GET /v2.1/0d772b180b3c41e2ae2eba61c236b149/servers/detail?all_tenants=True&changes-since=2018-06-28T15%3A45%3A54.642651%2B00%3A00 HTTP/1.1" status: 500 len: 621 time: 0.3303251
2018-06-28 17:51:17.869 26839 DEBUG nova.osapi_compute.wsgi.server [req-c80f54f7-614f-4115-b85f-bcedec63f052 - - - - -] (26839) accepted ('10.0.20.26', 58368) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 17:51:17.901 26839 WARNING keystonemiddleware.auth_token [req-c80f54f7-614f-4115-b85f-bcedec63f052 - - - - -] Using the in-process token cache is deprecated as of the 4.2.0 release and may be removed in the 5.0.0 release or the 'O' development cycle. The in-process cache causes inconsistent results and high memory usage. When the feature is removed the auth_token middleware will not cache tokens by default which may result in performance issues. It is recommended to use  memcache for the auth_token token cache by setting the memcached_servers option.
2018-06-28 17:51:19.941 26839 DEBUG nova.api.openstack.wsgi [req-f30ee60c-395a-4cd9-898f-1c9cae42ff77 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa0592210>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:51:19.948 26839 DEBUG nova.compute.api [req-f30ee60c-395a-4cd9-898f-1c9cae42ff77 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Failed to fetch instance by id tempest-INSTANCE_SAMPLE-1530200757 get /usr/lib/python2.7/site-packages/nova/compute/api.py:2329
2018-06-28 17:51:19.950 26839 INFO nova.api.openstack.wsgi [req-f30ee60c-395a-4cd9-898f-1c9cae42ff77 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] HTTP exception thrown: Impossibile trovare l'istanza tempest-INSTANCE_SAMPLE-1530200757.
2018-06-28 17:51:19.951 26839 DEBUG nova.api.openstack.wsgi [req-f30ee60c-395a-4cd9-898f-1c9cae42ff77 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Returning 404 to user: Impossibile trovare l'istanza tempest-INSTANCE_SAMPLE-1530200757. __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 17:51:19.956 26839 INFO nova.osapi_compute.wsgi.server [req-f30ee60c-395a-4cd9-898f-1c9cae42ff77 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers/tempest-INSTANCE_SAMPLE-1530200757 HTTP/1.1" status: 404 len: 532 time: 2.0689030
2018-06-28 17:51:19.994 26839 DEBUG nova.api.openstack.wsgi [req-7736aa87-5084-4613-afe6-08694dae8a75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.index of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa06b2d50>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:51:20.005 26839 DEBUG nova.compute.api [req-7736aa87-5084-4613-afe6-08694dae8a75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Searching by: {'deleted': False, 'project_id': u'a4257ab4c6fa41fa9a1bbb8768014ddb', u'name': u'tempest-INSTANCE_SAMPLE-1530200757'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 17:51:20.055 26839 DEBUG oslo_db.sqlalchemy.engines [req-7736aa87-5084-4613-afe6-08694dae8a75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 17:51:20.105 26839 DEBUG oslo_concurrency.lockutils [req-7736aa87-5084-4613-afe6-08694dae8a75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:51:20.109 26839 DEBUG oslo_concurrency.lockutils [req-7736aa87-5084-4613-afe6-08694dae8a75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.004s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:51:20.137 26839 DEBUG oslo_db.sqlalchemy.engines [req-7736aa87-5084-4613-afe6-08694dae8a75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 17:51:20.271 26839 DEBUG nova.compute.api [req-7736aa87-5084-4613-afe6-08694dae8a75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),a007229b-3aa8-4995-b876-a3a23b26e694(default) load_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:236
2018-06-28 17:51:20.273 26839 DEBUG nova.compute.api [req-7736aa87-5084-4613-afe6-08694dae8a75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 17:51:20.273 26839 DEBUG nova.compute.api [req-7736aa87-5084-4613-afe6-08694dae8a75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Listing 1000 instances in cell a007229b-3aa8-4995-b876-a3a23b26e694(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 17:51:20.275 26839 DEBUG oslo_concurrency.lockutils [req-7736aa87-5084-4613-afe6-08694dae8a75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:51:20.281 26839 DEBUG oslo_concurrency.lockutils [req-7736aa87-5084-4613-afe6-08694dae8a75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:51:20.306 26839 DEBUG oslo_db.sqlalchemy.engines [req-7736aa87-5084-4613-afe6-08694dae8a75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-28 17:51:20.410 26839 INFO nova.osapi_compute.wsgi.server [req-7736aa87-5084-4613-afe6-08694dae8a75 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers?name=tempest-INSTANCE_SAMPLE-1530200757 HTTP/1.1" status: 200 len: 784 time: 0.4316819
2018-06-28 17:51:20.443 26839 DEBUG nova.api.openstack.wsgi [req-cda4ec27-3728-4a52-afa2-8f31d531a585 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa0592210>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:51:20.449 26839 DEBUG nova.compute.api [req-cda4ec27-3728-4a52-afa2-8f31d531a585 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] [instance: 071f01a3-1f27-4a26-aaec-b12423ffa7aa] Fetching instance by UUID get /usr/lib/python2.7/site-packages/nova/compute/api.py:2324
2018-06-28 17:51:20.478 26839 DEBUG oslo_concurrency.lockutils [req-cda4ec27-3728-4a52-afa2-8f31d531a585 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:51:20.479 26839 DEBUG oslo_concurrency.lockutils [req-cda4ec27-3728-4a52-afa2-8f31d531a585 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions [req-cda4ec27-3728-4a52-afa2-8f31d531a585 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Unexpected exception in API method: TypeError: 'NoneType' object is not iterable
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions Traceback (most recent call last):
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/extensions.py", line 336, in wrapped
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions     return f(*args, **kwargs)
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/servers.py", line 442, in show
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions     return self._view_builder.show(req, instance)
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 145, in show
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions     extend_address),
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 252, in _get_addresses
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions     networks = common.get_networks_for_instance(context, instance)
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 326, in get_networks_for_instance
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions     return get_networks_for_instance_from_nw_info(nw_info)
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 293, in get_networks_for_instance_from_nw_info
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions     for vif in nw_info:
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions TypeError: 'NoneType' object is not iterable
2018-06-28 17:51:20.917 26839 ERROR nova.api.openstack.extensions 
2018-06-28 17:51:20.920 26839 INFO nova.api.openstack.wsgi [req-cda4ec27-3728-4a52-afa2-8f31d531a585 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] HTTP exception thrown: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'>
2018-06-28 17:51:20.921 26839 DEBUG nova.api.openstack.wsgi [req-cda4ec27-3728-4a52-afa2-8f31d531a585 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Returning 500 to user: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'> __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 17:51:20.923 26839 INFO nova.osapi_compute.wsgi.server [req-cda4ec27-3728-4a52-afa2-8f31d531a585 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers/071f01a3-1f27-4a26-aaec-b12423ffa7aa HTTP/1.1" status: 500 len: 621 time: 0.4952831
2018-06-28 17:51:20.949 26839 DEBUG nova.api.openstack.wsgi [req-99a89db4-7df5-468e-9065-0da5070162ff 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa061ff50>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:51:20.953 26839 DEBUG nova.compute.api [req-99a89db4-7df5-468e-9065-0da5070162ff 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Searching by: {'deleted': False, 'project_id': u'a4257ab4c6fa41fa9a1bbb8768014ddb'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 17:51:20.968 26839 DEBUG oslo_concurrency.lockutils [req-99a89db4-7df5-468e-9065-0da5070162ff 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:51:20.969 26839 DEBUG oslo_concurrency.lockutils [req-99a89db4-7df5-468e-9065-0da5070162ff 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:51:21.071 26839 DEBUG nova.compute.api [req-99a89db4-7df5-468e-9065-0da5070162ff 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 17:51:21.072 26839 DEBUG nova.compute.api [req-99a89db4-7df5-468e-9065-0da5070162ff 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Listing 1000 instances in cell a007229b-3aa8-4995-b876-a3a23b26e694(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 17:51:21.073 26839 DEBUG oslo_concurrency.lockutils [req-99a89db4-7df5-468e-9065-0da5070162ff 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:51:21.073 26839 DEBUG oslo_concurrency.lockutils [req-99a89db4-7df5-468e-9065-0da5070162ff 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions [req-99a89db4-7df5-468e-9065-0da5070162ff 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Unexpected exception in API method: TypeError: 'NoneType' object is not iterable
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions Traceback (most recent call last):
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/extensions.py", line 336, in wrapped
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions     return f(*args, **kwargs)
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/validation/__init__.py", line 181, in wrapper
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions     return func(*args, **kwargs)
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/validation/__init__.py", line 181, in wrapper
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions     return func(*args, **kwargs)
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/servers.py", line 168, in detail
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions     servers = self._get_servers(req, is_detail=True)
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/servers.py", line 323, in _get_servers
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions     response = self._view_builder.detail(req, instance_list)
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 199, in detail
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions     show_extra_specs)
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 213, in _list_view
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions     for server in servers]
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 145, in show
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions     extend_address),
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 252, in _get_addresses
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions     networks = common.get_networks_for_instance(context, instance)
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 326, in get_networks_for_instance
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions     return get_networks_for_instance_from_nw_info(nw_info)
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 293, in get_networks_for_instance_from_nw_info
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions     for vif in nw_info:
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions TypeError: 'NoneType' object is not iterable
2018-06-28 17:51:21.173 26839 ERROR nova.api.openstack.extensions 
2018-06-28 17:51:21.175 26839 INFO nova.api.openstack.wsgi [req-99a89db4-7df5-468e-9065-0da5070162ff 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] HTTP exception thrown: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'>
2018-06-28 17:51:21.177 26839 DEBUG nova.api.openstack.wsgi [req-99a89db4-7df5-468e-9065-0da5070162ff 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Returning 500 to user: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'> __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 17:51:21.180 26839 INFO nova.osapi_compute.wsgi.server [req-99a89db4-7df5-468e-9065-0da5070162ff 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers/detail HTTP/1.1" status: 500 len: 621 time: 0.2397110
2018-06-28 17:51:32.070 26839 DEBUG nova.osapi_compute.wsgi.server [req-99a89db4-7df5-468e-9065-0da5070162ff 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] (26839) accepted ('10.0.20.26', 58396) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:883
2018-06-28 17:51:32.620 26839 INFO nova.osapi_compute.wsgi.server [req-4390fba0-a86f-4787-affd-755978644f39 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb HTTP/1.1" status: 404 len: 382 time: 0.5477679
2018-06-28 17:51:32.642 26839 DEBUG nova.api.openstack.wsgi [req-9784b832-83cd-4da2-be8f-fef9e4e662cf 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7feaa0a91ed0>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:51:32.645 26839 INFO nova.osapi_compute.wsgi.server [req-9784b832-83cd-4da2-be8f-fef9e4e662cf 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/ HTTP/1.1" status: 200 len: 783 time: 0.0107348
2018-06-28 17:51:33.056 26839 DEBUG nova.api.openstack.wsgi [req-c48d7cc8-de69-4f78-8cd4-52db473ece1f 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7feaa061ff50>>' _process_stack /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:612
2018-06-28 17:51:33.063 26839 DEBUG nova.compute.api [req-c48d7cc8-de69-4f78-8cd4-52db473ece1f 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Searching by: {'deleted': False, 'project_id': u'a4257ab4c6fa41fa9a1bbb8768014ddb'} get_all /usr/lib/python2.7/site-packages/nova/compute/api.py:2356
2018-06-28 17:51:33.078 26839 DEBUG oslo_concurrency.lockutils [req-c48d7cc8-de69-4f78-8cd4-52db473ece1f 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:51:33.079 26839 DEBUG oslo_concurrency.lockutils [req-c48d7cc8-de69-4f78-8cd4-52db473ece1f 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:51:33.195 26839 DEBUG nova.compute.api [req-c48d7cc8-de69-4f78-8cd4-52db473ece1f 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Skipping already-collected cell0 list _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2556
2018-06-28 17:51:33.196 26839 DEBUG nova.compute.api [req-c48d7cc8-de69-4f78-8cd4-52db473ece1f 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Listing 1000 instances in cell a007229b-3aa8-4995-b876-a3a23b26e694(default) _get_instances_by_filters_all_cells /usr/lib/python2.7/site-packages/nova/compute/api.py:2559
2018-06-28 17:51:33.199 26839 DEBUG oslo_concurrency.lockutils [req-c48d7cc8-de69-4f78-8cd4-52db473ece1f 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-28 17:51:33.200 26839 DEBUG oslo_concurrency.lockutils [req-c48d7cc8-de69-4f78-8cd4-52db473ece1f 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Lock "a007229b-3aa8-4995-b876-a3a23b26e694" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions [req-c48d7cc8-de69-4f78-8cd4-52db473ece1f 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Unexpected exception in API method: TypeError: 'NoneType' object is not iterable
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions Traceback (most recent call last):
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/extensions.py", line 336, in wrapped
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions     return f(*args, **kwargs)
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/validation/__init__.py", line 181, in wrapper
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions     return func(*args, **kwargs)
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/validation/__init__.py", line 181, in wrapper
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions     return func(*args, **kwargs)
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/servers.py", line 168, in detail
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions     servers = self._get_servers(req, is_detail=True)
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/servers.py", line 323, in _get_servers
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions     response = self._view_builder.detail(req, instance_list)
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 199, in detail
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions     show_extra_specs)
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 213, in _list_view
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions     for server in servers]
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 145, in show
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions     extend_address),
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/views/servers.py", line 252, in _get_addresses
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions     networks = common.get_networks_for_instance(context, instance)
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 326, in get_networks_for_instance
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions     return get_networks_for_instance_from_nw_info(nw_info)
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/common.py", line 293, in get_networks_for_instance_from_nw_info
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions     for vif in nw_info:
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions TypeError: 'NoneType' object is not iterable
2018-06-28 17:51:33.371 26839 ERROR nova.api.openstack.extensions 
2018-06-28 17:51:33.374 26839 INFO nova.api.openstack.wsgi [req-c48d7cc8-de69-4f78-8cd4-52db473ece1f 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] HTTP exception thrown: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'>
2018-06-28 17:51:33.376 26839 DEBUG nova.api.openstack.wsgi [req-c48d7cc8-de69-4f78-8cd4-52db473ece1f 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] Returning 500 to user: Errore API non previsto. Segnalarlo a http://bugs.launchpad.net/nova/ e allegare il log Nova API, se possibile.
<type 'exceptions.TypeError'> __call__ /usr/lib/python2.7/site-packages/nova/api/openstack/wsgi.py:1029
2018-06-28 17:51:33.378 26839 INFO nova.osapi_compute.wsgi.server [req-c48d7cc8-de69-4f78-8cd4-52db473ece1f 35abf12be7224ba89c47fb5c86dbc747 a4257ab4c6fa41fa9a1bbb8768014ddb - 02e89a8673da41529ece5743b8bdc4b1 02e89a8673da41529ece5743b8bdc4b1] 10.0.20.26 "GET /v2.1/a4257ab4c6fa41fa9a1bbb8768014ddb/servers/detail HTTP/1.1" status: 500 len: 623 time: 0.3325050
