2018-06-27 21:22:36.331 9006 DEBUG oslo_db.sqlalchemy.engines [req-f432cedf-a09a-4df2-baab-463564aea146 208266dbe41d47fb8b0ff10e90c6527c 55c7ae11597246569bffbdf80196c963 - 23f376fa93404c40aeaaa52245838cf5 23f376fa93404c40aeaaa52245838cf5] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-27 21:22:40.659 9006 DEBUG oslo_concurrency.lockutils [req-f432cedf-a09a-4df2-baab-463564aea146 208266dbe41d47fb8b0ff10e90c6527c 55c7ae11597246569bffbdf80196c963 - 23f376fa93404c40aeaaa52245838cf5 23f376fa93404c40aeaaa52245838cf5] Lock "72c9866c-097e-4830-88cc-fbc19314d896" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-06-27 21:22:40.665 9006 DEBUG oslo_concurrency.lockutils [req-f432cedf-a09a-4df2-baab-463564aea146 208266dbe41d47fb8b0ff10e90c6527c 55c7ae11597246569bffbdf80196c963 - 23f376fa93404c40aeaaa52245838cf5 23f376fa93404c40aeaaa52245838cf5] Lock "72c9866c-097e-4830-88cc-fbc19314d896" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.006s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-06-27 21:22:40.691 9006 DEBUG oslo_db.sqlalchemy.engines [req-f432cedf-a09a-4df2-baab-463564aea146 208266dbe41d47fb8b0ff10e90c6527c 55c7ae11597246569bffbdf80196c963 - 23f376fa93404c40aeaaa52245838cf5 23f376fa93404c40aeaaa52245838cf5] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server [req-f432cedf-a09a-4df2-baab-463564aea146 208266dbe41d47fb8b0ff10e90c6527c 55c7ae11597246569bffbdf80196c963 - 23f376fa93404c40aeaaa52245838cf5 23f376fa93404c40aeaaa52245838cf5] Exception during message handling: AttributeError: 'unicode' object has no attribute 'is_admin'
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 160, in _process_incoming
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 213, in dispatch
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 183, in _do_dispatch
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/conductor/manager.py", line 1125, in schedule_and_build_instances
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     instance.create()
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_versionedobjects/base.py", line 226, in wrapper
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     return fn(self, *args, **kwargs)
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/objects/instance.py", line 554, in create
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     db_inst = db.instance_create(self._context, updates)
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/db/api.py", line 734, in instance_create
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     return IMPL.instance_create(context, values)
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py", line 135, in wrapper
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     return f(*args, **kwargs)
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 150, in wrapper
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     ectxt.value = e.inner_exc
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     self.force_reraise()
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     six.reraise(self.type_, self.value, self.tb)
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 138, in wrapper
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     return f(*args, **kwargs)
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py", line 180, in wrapped
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     return f(context, *args, **kwargs)
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py", line 1103, in instance_create
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     ec2_instance_create(instance_ref['uuid'])
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py", line 134, in wrapper
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     nova.context.require_context(args[0])
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/nova/context.py", line 343, in require_context
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server     if not ctxt.is_admin and not is_user_context(ctxt):
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server AttributeError: 'unicode' object has no attribute 'is_admin'
2018-06-27 21:22:40.766 9006 ERROR oslo_messaging.rpc.server 
