2018-09-14 14:59:10.823 4132 DEBUG oslo_db.sqlalchemy.engines [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-14 14:59:16.339 4132 DEBUG oslo_concurrency.lockutils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lock "0dfb75e5-6834-4e0b-b55a-d61c751537ce" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 14:59:16.351 4132 DEBUG oslo_concurrency.lockutils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lock "0dfb75e5-6834-4e0b-b55a-d61c751537ce" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.012s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 14:59:16.391 4132 DEBUG oslo_db.sqlalchemy.engines [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-14 14:59:16.665 4132 DEBUG nova.context [req-21591405-29db-4704-9c99-c2a9826d895c - - - - -] Found 2 cells: 00000000-0000-0000-0000-000000000000(cell0),0dfb75e5-6834-4e0b-b55a-d61c751537ce(default) load_cells /usr/lib/python2.7/site-packages/nova/context.py:508
2018-09-14 14:59:16.667 4132 DEBUG oslo_concurrency.lockutils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 14:59:16.669 4132 DEBUG oslo_concurrency.lockutils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 14:59:16.672 4132 DEBUG oslo_concurrency.lockutils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lock "0dfb75e5-6834-4e0b-b55a-d61c751537ce" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 14:59:16.673 4132 DEBUG oslo_concurrency.lockutils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lock "0dfb75e5-6834-4e0b-b55a-d61c751537ce" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 14:59:16.714 4132 DEBUG oslo_db.sqlalchemy.engines [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-14 14:59:16.751 4132 DEBUG nova.quota [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Getting quotas for project 8858be34637542409f7c15827d2a3c85. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:442
2018-09-14 14:59:16.765 4132 DEBUG nova.quota [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Getting quotas for user dea50fe04d1c48a58d0e804f1b2dd2ab and project 8858be34637542409f7c15827d2a3c85. Resources: set(['instances', 'ram', 'cores']) _get_quotas /usr/lib/python2.7/site-packages/nova/quota.py:434
2018-09-14 14:59:16.796 4132 DEBUG oslo_concurrency.lockutils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lock "0dfb75e5-6834-4e0b-b55a-d61c751537ce" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 14:59:16.797 4132 DEBUG oslo_concurrency.lockutils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lock "0dfb75e5-6834-4e0b-b55a-d61c751537ce" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 14:59:16.798 4132 WARNING nova.image.glance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] No protocol specified in for api_server 'http://10.0.20.24:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-14 14:59:16.871 4132 DEBUG nova.notifications.objects.base [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-14 14:59:16.876 4132 DEBUG nova.objects.instance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lazy-loading 'tags' on Instance uuid 416ed487-b15b-4278-a995-d8311be4ea4a obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-14 14:59:16.949 4132 DEBUG nova.conductor.manager [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] [instance: 416ed487-b15b-4278-a995-d8311be4ea4a] block_device_mapping [BlockDeviceMapping(attachment_id=<?>,boot_index=0,connection_info=None,created_at=<?>,delete_on_termination=True,deleted=<?>,deleted_at=<?>,destination_type='local',device_name=None,device_type='disk',disk_bus=None,guest_format=None,id=<?>,image_id='c931f7b0-cc1c-4269-8474-ab6e94c7d2c5',instance=<?>,instance_uuid=<?>,no_device=False,snapshot_id=None,source_type='image',tag=None,updated_at=<?>,volume_id=None,volume_size=None)] _create_block_device_mapping /usr/lib/python2.7/site-packages/nova/conductor/manager.py:968
2018-09-14 14:59:16.953 4132 DEBUG oslo_concurrency.lockutils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lock "0dfb75e5-6834-4e0b-b55a-d61c751537ce" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 14:59:16.953 4132 DEBUG oslo_concurrency.lockutils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lock "0dfb75e5-6834-4e0b-b55a-d61c751537ce" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 14:59:17.044 4132 DEBUG oslo_concurrency.lockutils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lock "0dfb75e5-6834-4e0b-b55a-d61c751537ce" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-09-14 14:59:17.045 4132 DEBUG oslo_concurrency.lockutils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lock "0dfb75e5-6834-4e0b-b55a-d61c751537ce" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s inner /usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-09-14 14:59:17.719 4123 WARNING nova.image.glance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] No protocol specified in for api_server 'http://10.0.20.24:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-14 14:59:17.820 4123 DEBUG nova.notifications.objects.base [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-14 14:59:18.337 4128 WARNING nova.image.glance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] No protocol specified in for api_server 'http://10.0.20.24:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-14 14:59:18.486 4128 DEBUG nova.notifications.objects.base [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-14 14:59:19.658 4126 WARNING nova.image.glance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] No protocol specified in for api_server 'http://10.0.20.24:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-14 14:59:19.735 4126 DEBUG nova.notifications.objects.base [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-14 14:59:20.227 4124 WARNING nova.image.glance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] No protocol specified in for api_server 'http://10.0.20.24:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-14 14:59:20.341 4124 DEBUG nova.notifications.objects.base [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-14 14:59:20.682 4123 WARNING nova.image.glance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] No protocol specified in for api_server 'http://10.0.20.24:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-14 14:59:20.712 4123 DEBUG nova.notifications.objects.base [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-14 14:59:31.819 4123 WARNING nova.image.glance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] No protocol specified in for api_server 'http://10.0.20.24:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-14 14:59:31.843 4123 DEBUG nova.notifications.objects.base [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-14 14:59:32.589 4127 WARNING nova.image.glance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] No protocol specified in for api_server 'http://10.0.20.24:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-14 14:59:32.681 4127 DEBUG nova.notifications.objects.base [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-14 14:59:33.092 4128 WARNING nova.image.glance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] No protocol specified in for api_server 'http://10.0.20.24:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-14 14:59:33.137 4128 DEBUG nova.notifications.objects.base [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-14 14:59:36.371 4129 WARNING nova.image.glance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] No protocol specified in for api_server 'http://10.0.20.24:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-14 14:59:36.474 4129 DEBUG nova.notifications.objects.base [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-14 14:59:36.716 4123 WARNING nova.image.glance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] No protocol specified in for api_server 'http://10.0.20.24:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)
2018-09-14 14:59:36.732 4123 DEBUG nova.notifications.objects.base [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-14 14:59:36.832 4127 ERROR nova.scheduler.utils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] [instance: 416ed487-b15b-4278-a995-d8311be4ea4a] Error from last host: localhost.localdomain (node localhost.localdomain): [u'Traceback (most recent call last):\n', u'  File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 1855, in _do_build_and_run_instance\n    filter_properties)\n', u'  File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 2094, in _build_and_run_instance\n    instance_uuid=instance.uuid, reason=six.text_type(e))\n', u"RescheduledException: Build of instance 416ed487-b15b-4278-a995-d8311be4ea4a was re-scheduled: operation failed: domain 'instance-00000004' already exists with uuid a9f403e8-2b10-43e7-a4f9-3cd09cd0242b\n"]
2018-09-14 14:59:36.868 4127 DEBUG oslo_db.sqlalchemy.engines [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] MySQL server mode set to STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION _check_effective_sql_mode /usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:285
2018-09-14 14:59:37.561 4127 WARNING nova.scheduler.utils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Failed to compute_task_build_instances: No valid host was found. There are not enough hosts available.
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 232, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/manager.py", line 150, in select_destinations
    alloc_reqs_by_rp_uuid, provider_summaries)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/filter_scheduler.py", line 110, in select_destinations
    raise exception.NoValidHost(reason=reason)

NoValidHost: No valid host was found. There are not enough hosts available.
: NoValidHost_Remote: No valid host was found. There are not enough hosts available.
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 232, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/manager.py", line 150, in select_destinations
    alloc_reqs_by_rp_uuid, provider_summaries)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/filter_scheduler.py", line 110, in select_destinations
    raise exception.NoValidHost(reason=reason)

NoValidHost: No valid host was found. There are not enough hosts available.
2018-09-14 14:59:37.563 4127 WARNING nova.scheduler.utils [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] [instance: 416ed487-b15b-4278-a995-d8311be4ea4a] Setting instance to ERROR state.: NoValidHost_Remote: No valid host was found. There are not enough hosts available.
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 232, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/manager.py", line 150, in select_destinations
    alloc_reqs_by_rp_uuid, provider_summaries)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/filter_scheduler.py", line 110, in select_destinations
    raise exception.NoValidHost(reason=reason)

NoValidHost: No valid host was found. There are not enough hosts available.
2018-09-14 14:59:37.703 4127 WARNING nova.image.glance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] No protocol specified in for api_server 'http://10.0.20.24:9292', please update [glance] api_servers with fully qualified url including scheme (http / https): NoValidHost_Remote: No valid host was found. There are not enough hosts available.
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 232, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/manager.py", line 150, in select_destinations
    alloc_reqs_by_rp_uuid, provider_summaries)

  File "/usr/lib/python2.7/site-packages/nova/scheduler/filter_scheduler.py", line 110, in select_destinations
    raise exception.NoValidHost(reason=reason)

NoValidHost: No valid host was found. There are not enough hosts available.
2018-09-14 14:59:37.705 4127 DEBUG nova.objects.instance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lazy-loading 'metadata' on Instance uuid 416ed487-b15b-4278-a995-d8311be4ea4a obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-14 14:59:37.815 4127 DEBUG nova.objects.instance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lazy-loading 'info_cache' on Instance uuid 416ed487-b15b-4278-a995-d8311be4ea4a obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-14 14:59:37.961 4127 DEBUG nova.notifications.objects.base [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object' populate_schema /usr/lib/python2.7/site-packages/nova/notifications/objects/base.py:125
2018-09-14 14:59:37.966 4127 DEBUG nova.objects.instance [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] Lazy-loading 'tags' on Instance uuid 416ed487-b15b-4278-a995-d8311be4ea4a obj_load_attr /usr/lib/python2.7/site-packages/nova/objects/instance.py:1049
2018-09-14 14:59:38.064 4127 DEBUG nova.network.neutronv2.api [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] [instance: 416ed487-b15b-4278-a995-d8311be4ea4a] deallocate_for_instance() deallocate_for_instance /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:1182
2018-09-14 14:59:38.214 4127 DEBUG nova.network.neutronv2.api [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] [instance: 416ed487-b15b-4278-a995-d8311be4ea4a] Instance cache missing network info. _get_preexisting_port_ids /usr/lib/python2.7/site-packages/nova/network/neutronv2/api.py:2238
2018-09-14 14:59:38.281 4127 DEBUG nova.network.base_api [req-9061cf36-da49-4105-b549-ddd44e44c424 dea50fe04d1c48a58d0e804f1b2dd2ab 8858be34637542409f7c15827d2a3c85 - b22d36b7af8d446b821bbcafe18ce051 b22d36b7af8d446b821bbcafe18ce051] [instance: 416ed487-b15b-4278-a995-d8311be4ea4a] Updating instance_info_cache with network_info: [] update_instance_cache_with_nw_info /usr/lib/python2.7/site-packages/nova/network/base_api.py:48
